### PR TITLE
Minor modifications after testing

### PR DESCRIPTION
**Pull request by pwighton**
- `os.mkdirs()` is replaced by `os.makedirs()` so that the full directory path will be created if it doesn't exist
-  `pyyaml` is added to the list of required python packages
- `os.getcwd()` is replaced by `os.path.realpath()` to find `config.yaml` in a more robust way
- adds default `sep` parameters to `config.yaml` for coregistration
- command line parameters now override values in `config.yaml`

### CODE REVIEW

**Comment by pwighton** [comment]
@mnoergaard should the defaults for `sep` under coregistration also be added to the petsurfer nipype interfaces [here](https://github.com/mnoergaard/nipype/blob/e2a37fa01f4b0f3cc1bcb692f109fb2c61e96ac3/nipype/interfaces/freesurfer/registration.py#L460)?

**Review by avneet14027 — APPROVED** [review]

**Comment by mnoergaard** [comment]
Thanks @pwighton! it shouldn't be necessary to add the default to the interface because this is already the freesurfer default setting.

**Review by avneet14027 — APPROVED** [review]
I don't know what `sep` is in config. 
Other than that, the modifications look good!

**Comment by pwighton** [comment]
@avneet14027, @mnoergaard, what version of FreeSurfer are you testing with?  I was getting an error with coregistration FreeSurfer 7.2.0 until I added the `sep` param in the config.  I wish I had saved the log..

**Comment by avneet14027** [comment]
@pwighton I used Freesurfer 7.2.0 as well for testing but didn't get any errors

**Comment by pwighton** [comment]
Oh interesting... thanks.

**Comment by mnoergaard** [comment]
@pwighton I was also able to reproduce @avneet14027 success using the pipeline and FreeSurfer 7.2.0. Let me know if you want to see some of the outputs.

**Pull request merged**
